import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import { formatCurrency } from '../../utils/taxCalculations'
import toast from 'react-hot-toast'

export default function History({ userProfile }) {
  const [calculations, setCalculations] = useState([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('all') // all, personal, business
  const [selectedCalc, setSelectedCalc] = useState(null)
  const [deleting, setDeleting] = useState(null)

  useEffect(() => {
    fetchCalculations()
  }, [userProfile])

  const fetchCalculations = async () => {
    if (!userProfile?.id) return

    try {
      const { data, error } = await supabase
        .from('saved_calculations')
        .select('*')
        .eq('user_id', userProfile.id)
        .order('created_at', { ascending: false })

      if (error) throw error
      setCalculations(data || [])
    } catch (error) {
      console.error('Error fetching calculations:', error)
      toast.error('Failed to load saved analyses')
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async (id) => {
    if (!confirm('Are you sure you want to delete this analysis?')) return

    setDeleting(id)
    try {
      const { error } = await supabase
        .from('saved_calculations')
        .delete()
        .eq('id', id)

      if (error) throw error

      setCalculations(prev => prev.filter(c => c.id !== id))
      if (selectedCalc?.id === id) setSelectedCalc(null)
      toast.success('Analysis deleted')
    } catch (error) {
      console.error('Delete error:', error)
      toast.error('Failed to delete analysis')
    } finally {
      setDeleting(null)
    }
  }

  const handleDownload = (calc) => {
    const isPersonal = calc.calculation_type === 'personal'
    const data = calc.data
    const inputs = calc.inputs

    let content = ''

    if (isPersonal) {
      content = `
PERSONAL INCOME TAX ANALYSIS
============================
Generated: ${new Date(calc.created_at).toLocaleString('en-NG')}
Name: ${inputs?.name || 'Personal Tax Analysis'}

INPUTS
------
Monthly Gross Salary: ${formatCurrency(parseFloat(inputs?.monthlyGross) || 0)}
Annual Gross Income: ${formatCurrency(data?.annualGross || 0)}
Annual Rent Paid: ${formatCurrency(parseFloat(inputs?.annualRent) || 0)}
Pension Contribution: ${inputs?.hasPension ? 'Yes (8%)' : 'No'}
NHF Contribution: ${inputs?.hasNHF ? 'Yes (2.5%)' : 'No'}

DEDUCTIONS
----------
Pension: ${formatCurrency(data?.pension || 0)}
NHF: ${formatCurrency(data?.nhf || 0)}
Rent Relief: ${formatCurrency(data?.rentRelief || 0)}
Total Deductions: ${formatCurrency(data?.totalDeductions || 0)}

TAX CALCULATION
---------------
Taxable Income: ${formatCurrency(data?.taxableIncome || 0)}
Annual Tax Payable: ${formatCurrency(data?.netTax || 0)}
Monthly Tax: ${formatCurrency(data?.monthlyTax || 0)}
Effective Tax Rate: ${(data?.effectiveRate || 0).toFixed(2)}%
      `.trim()
    } else {
      content = `
CORPORATE INCOME TAX ANALYSIS
=============================
Generated: ${new Date(calc.created_at).toLocaleString('en-NG')}
Company: ${inputs?.companyName || 'Business Tax Analysis'}

FINANCIAL DATA
--------------
Annual Turnover: ${formatCurrency(data?.turnover || 0)}
Total Fixed Assets: ${formatCurrency(data?.assets || 0)}
Net Profit Before Tax: ${formatCurrency(parseFloat(inputs?.profit) || 0)}
Depreciation: ${formatCurrency(parseFloat(inputs?.depreciation) || 0)}
Fines/Penalties: ${formatCurrency(parseFloat(inputs?.fines) || 0)}
Capital Allowances: ${formatCurrency(parseFloat(inputs?.capitalAllowances) || 0)}

TAX CALCULATION
---------------
Classification: ${data?.isSmallBusiness ? 'Small Company' : 'Large Company'}
Assessable Profit: ${formatCurrency(data?.assessableProfit || 0)}
CIT Rate: ${data?.citRate || 0}%
Development Levy Rate: ${data?.developmentLevyRate || 0}%

TAX PAYABLE
-----------
Corporate Income Tax: ${formatCurrency(data?.cit || 0)}
Development Levy: ${formatCurrency(data?.developmentLevy || 0)}
Total Tax Payable: ${formatCurrency(data?.totalTax || 0)}

NOTE
----
${data?.note || ''}
      `.trim()
    }

    content += `

---
Generated by Taxify - Nigeria Tax Support Portal
Based on Nigeria Tax Act 2025 (effective Jan 2026)
    `

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${calc.calculation_type}-tax-analysis-${calc.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    toast.success('Report downloaded!')
  }

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-NG', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  const filteredCalculations = calculations.filter(calc => {
    if (filter === 'all') return true
    return calc.calculation_type === filter
  })

  const isCompany = userProfile?.user_type === 'company'

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Saved Analyses</h1>
          <p className="text-slate-600 mt-1">View, download, and manage your tax calculations</p>
        </div>
        <Link
          to={isCompany ? '/dashboard/business' : '/dashboard/personal'}
          className="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
        >
          <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
          New Analysis
        </Link>
      </div>

      {/* Filter Tabs */}
      <div className="flex space-x-1 bg-slate-100 rounded-lg p-1 w-fit">
        {[
          { id: 'all', label: 'All' },
          { id: 'personal', label: 'Personal' },
          { id: 'business', label: 'Business' }
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setFilter(tab.id)}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
              filter === tab.id
                ? 'bg-white text-slate-900 shadow-sm'
                : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* List */}
        <div className="lg:col-span-2">
          {loading ? (
            <div className="bg-white rounded-xl border border-slate-200 p-8 text-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-green-600 mx-auto"></div>
              <p className="text-slate-500 mt-4">Loading analyses...</p>
            </div>
          ) : filteredCalculations.length > 0 ? (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
              <div className="divide-y divide-slate-100">
                {filteredCalculations.map((calc) => (
                  <div 
                    key={calc.id}
                    onClick={() => setSelectedCalc(calc)}
                    className={`p-4 flex items-center justify-between cursor-pointer transition-colors ${
                      selectedCalc?.id === calc.id ? 'bg-green-50' : 'hover:bg-slate-50'
                    }`}
                  >
                    <div className="flex items-center space-x-4">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${
                        calc.calculation_type === 'business'
                          ? 'bg-blue-100 text-blue-600'
                          : 'bg-green-100 text-green-600'
                      }`}>
                        {calc.calculation_type === 'business' ? (
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                          </svg>
                        ) : (
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                          </svg>
                        )}
                      </div>
                      <div className="min-w-0">
                        <p className="font-medium text-slate-900 truncate">
                          {calc.inputs?.companyName || calc.inputs?.name || `${calc.calculation_type === 'business' ? 'Business' : 'Personal'} Analysis`}
                        </p>
                        <p className="text-sm text-slate-500">{formatDate(calc.created_at)}</p>
                      </div>
                    </div>
                    <div className="flex items-center space-x-4">
                      <div className="text-right">
                        <p className="font-semibold text-slate-900">
                          {formatCurrency(calc.data?.totalTax || calc.data?.netTax || 0)}
                        </p>
                        <p className="text-xs text-slate-500">Tax</p>
                      </div>
                      <div className="flex space-x-1">
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            handleDownload(calc)
                          }}
                          className="p-2 text-slate-400 hover:text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                          title="Download"
                        >
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                          </svg>
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation()
                            handleDelete(calc.id)
                          }}
                          disabled={deleting === calc.id}
                          className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors disabled:opacity-50"
                          title="Delete"
                        >
                          {deleting === calc.id ? (
                            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-red-600"></div>
                          ) : (
                            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-xl border border-slate-200 p-12 text-center">
              <svg className="w-16 h-16 text-slate-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <h3 className="text-lg font-medium text-slate-900 mb-2">No analyses found</h3>
              <p className="text-slate-500 mb-6">
                {filter !== 'all' 
                  ? `No ${filter} tax analyses yet`
                  : 'Create your first tax calculation to see it here'}
              </p>
              <Link
                to={isCompany ? '/dashboard/business' : '/dashboard/personal'}
                className="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 transition-colors"
              >
                Create Analysis
              </Link>
            </div>
          )}
        </div>

        {/* Detail Panel */}
        <div className="lg:col-span-1">
          {selectedCalc ? (
            <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 sticky top-8">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold text-slate-900">Analysis Details</h3>
                <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                  selectedCalc.calculation_type === 'business'
                    ? 'bg-blue-100 text-blue-700'
                    : 'bg-green-100 text-green-700'
                }`}>
                  {selectedCalc.calculation_type === 'business' ? 'Business' : 'Personal'}
                </span>
              </div>

              <div className="space-y-4">
                <div>
                  <p className="text-sm text-slate-500">Name</p>
                  <p className="font-medium text-slate-900">
                    {selectedCalc.inputs?.companyName || selectedCalc.inputs?.name || 'Tax Analysis'}
                  </p>
                </div>

                <div>
                  <p className="text-sm text-slate-500">Created</p>
                  <p className="font-medium text-slate-900">{formatDate(selectedCalc.created_at)}</p>
                </div>

                {selectedCalc.calculation_type === 'personal' ? (
                  <>
                    <div>
                      <p className="text-sm text-slate-500">Annual Income</p>
                      <p className="font-medium text-slate-900">
                        {formatCurrency(selectedCalc.data?.annualGross || 0)}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-slate-500">Taxable Income</p>
                      <p className="font-medium text-slate-900">
                        {formatCurrency(selectedCalc.data?.taxableIncome || 0)}
                      </p>
                    </div>
                  </>
                ) : (
                  <>
                    <div>
                      <p className="text-sm text-slate-500">Turnover</p>
                      <p className="font-medium text-slate-900">
                        {formatCurrency(selectedCalc.data?.turnover || 0)}
                      </p>
                    </div>
                    <div>
                      <p className="text-sm text-slate-500">Classification</p>
                      <p className="font-medium text-slate-900">
                        {selectedCalc.data?.isSmallBusiness ? 'Small Company' : 'Large Company'}
                      </p>
                    </div>
                  </>
                )}

                <div className="pt-4 border-t border-slate-200">
                  <p className="text-sm text-slate-500">Tax Payable</p>
                  <p className="text-2xl font-bold text-green-600">
                    {formatCurrency(selectedCalc.data?.totalTax || selectedCalc.data?.netTax || 0)}
                  </p>
                </div>

                <div className="pt-4 space-y-2">
                  <button
                    onClick={() => handleDownload(selectedCalc)}
                    className="w-full bg-green-600 text-white px-4 py-2.5 rounded-lg font-medium hover:bg-green-700 transition-colors flex items-center justify-center"
                  >
                    <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download Report
                  </button>
                  <button
                    onClick={() => handleDelete(selectedCalc.id)}
                    className="w-full bg-red-50 text-red-600 px-4 py-2.5 rounded-lg font-medium hover:bg-red-100 transition-colors"
                  >
                    Delete Analysis
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-slate-50 rounded-xl border-2 border-dashed border-slate-200 p-8 text-center">
              <svg className="w-12 h-12 text-slate-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
              <p className="text-slate-500 text-sm">Select an analysis to view details</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
